server {
    listen 80;
    listen [::]:80;
    server_name sub-dev.nmediax.com ;
    location ^~ /.well-known {
        root /app/ssl-folder/sub-dev.nmediax.com;
        break;
    }
    location / {
        return 301 https://$host$request_uri;
    }

}


server {
    #listen 80;
    server_name sub-dev.nmediax.com ;
    listen 443 ssl;
    listen [::]:443 ssl;
    ssl_certificate /etc/letsencrypt/live/sub-dev.nmediax.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sub-dev.nmediax.com/privkey.pem;
    location ~ '^((/aapi/v1.0/[/A-Za-z0-9._-]*)|(/sapi/v1.0/[/A-Za-z0-9._-]*)|(/api/v1.0/[/A-Za-z0-9._-]*)|(/iapi/v1.0/[/A-Za-z0-9._-]*))$' {
        include uwsgi_params;
        uwsgi_pass cremail-dev:8080;
        proxy_set_header Host "$http_host";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        client_max_body_size 10M;
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
        add_header "Access-Control-Allow-Headers" "Authorization, Origin, X-Requested-With, Content-Type, Accept";
        if ($request_method = OPTIONS) {
            break;
        }
    }
}