
server {
  listen 80;
  listen [::]:80;

  server_name ~^(?<subdomain>.+)\.cradmin\.com ~^(?<subdomain>.+)\.nmediax\.com *.nmediax.com ;

  location ^~ /.well-known {

    set $host_without_www $host;
    if ($host ~* ^www\.(.*)) {
      set $host_without_www $1;

    }


    root /app/ssl-folder/$host_without_www;
    break;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}


server {

  server_name *.nmediax.com ;
  rewrite ^/(.*)/$ /$1 permanent;
  listen 443 ssl;
  listen [::]:443 ssl;


  root /app/ssl-folder/$cert_folder;


  set $sslfolder nmediax.com;

  proxy_intercept_errors on;


  location / {
    set $baseurl https://storage.googleapis.com;


    if ($request_uri ~ ^(.*/)/($|\?.*)) {
      return 200 '$1$2';
      return 301 $1$2;
    }


    if ($host = 'nmediax.com') {
      proxy_pass http://webadmin:6000;


      set $temp_cache 2$temp_cache;
      break;


    }
    if ($host = 'app.nmediax.com' ) {
      set $temp_cache1 4$temp_cache1;
    }

    if ($request_uri ~ .*v1.*) {

      set $temp_cache1 5$temp_cache1;

    }

    if ($request_uri ~ .*locales.*) {
      set $temp_cache1 5$temp_cache1;

    }


    if ($temp_cache1 = 54) {
      proxy_pass http://webadmin:6000;
      set $temp_cache 2$temp_cache;

      break;

    }

    if ($host != 'nmediax.com' ) {
      set $temp_cache 1$temp_cache;
    }
    if ($uri = '/') {
      set $temp_cache 1$temp_cache;
    }

    if ($temp_cache = 11) {

      proxy_pass $baseurl/cur-layout-dev-data/$cert_folder/$cert_folder;

      break;

    }
    if ($temp_cache = 1 ) {

      proxy_pass $baseurl/cur-layout-dev-data/$cert_folder$request_uri;


    }


  }

  location ~ .(static)/(js|css|media)/(.+)$ {
    proxy_pass http://webadmin:6000;
  }
  location ^~ /sslcreate {

    include uwsgi_params;
    uwsgi_pass sslserver:8085;

  }

  location /error.html {
    proxy_pass https://storage.googleapis.com/cur_data_storage/error.html;

  }
  ssl_certificate /etc/letsencrypt/live/$cert_folder/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/$cert_folder/privkey.pem;


}

#}
