# DNS resolver (IMPORTANT for proxy_pass with variables)
resolver 10.96.0.10 valid=30s;
resolver_timeout 5s;

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    # LetsEncrypt ACME challenge
    location ^~ /.well-known/acme-challenge/ {

        set $host_without_www $host;

        if ($host ~* ^www\.(.*)$) {
            set $host_without_www $1;
        }

        root /app/ssl-folder/$host_without_www;
        allow all;
        default_type "text/plain";
        try_files $uri =404;
    }

    # Redirect HTTP → HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {

    listen 443 ssl;
    listen [::]:443 ssl;

    server_name *.storye.site;

    rewrite ^/(.*)/$ /$1 permanent;

    root /app/ssl-folder/$cert_folder;

    proxy_intercept_errors on;

    ssl_certificate /etc/letsencrypt/live/$cert_folder/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$cert_folder/privkey.pem;

    location / {

        # initialize variables
        set $temp_cache "";
        set $temp_cache1 "";

        set $baseurl https://assets.projectwhite.space;
        set $target_folder $cert_folder;

        # handle www subdomain
        if ($host ~* ^www\.) {
            set $target_folder www.$cert_folder;
        }

        # remove double trailing slash
        if ($request_uri ~ ^(.*/)/($|\?.*)) {
            return 301 $1$2;
        }

        # special rules
        if ($host = 'app.storye.site') {
            set $temp_cache1 4$temp_cache1;
        }

        if ($request_uri ~ .*v1.*) {
            set $temp_cache1 5$temp_cache1;
        }

        if ($request_uri ~ .*locales.*) {
            set $temp_cache1 5$temp_cache1;
        }

        if ($host != 'storye.site') {
            set $temp_cache 1$temp_cache;
        }

        if ($uri = '/') {
            set $temp_cache 1$temp_cache;
        }

        # root request
        if ($temp_cache = 11) {
            proxy_pass $baseurl/$target_folder/$target_folder;
            break;
        }

        # normal request
        if ($temp_cache = 1) {
            proxy_pass $baseurl/$target_folder$request_uri;
        }

    }

    location /error.html {
        proxy_pass https://storage.googleapis.com/cur_data_storage/error.html;
    }

}