server {
    listen 80;
    listen [::]:80;
    server_name ~^(?<subdomain>.+)\.devstorye\.us ~^(?<subdomain>.+)\.devstorye\.us *.devstorye.us devstorye.us;


    location ^~ /.well-known {

        break;
    }


    location / {
        set $baseurl https://storage.googleapis.com;

        if ($request_uri ~ ^(.*/)/($|\?.*)) {
            return 200 '$1$2';
            return 301 $1$2;
        }

        if ($host = 'devstorye.us' ) {
            set $temp_cache 1$temp_cache;
        }

        if ($uri = '/') {
            set $temp_cache 1$temp_cache;
        }

        if ($temp_cache = 11) {
            return 200 "$host";
            break;
        }
        if ($temp_cache = 1 ) {
            return 200 "$host $temp_cache $request_uri";
        }


    }
}


server {

    server_name devstorye.us *.devstorye.us;
    rewrite ^/(.*)/$ /$1 permanent;
    listen 443 ssl;
    listen [::]:443 ssl;


    proxy_intercept_errors on;


    location / {
        set $baseurl https://storage.googleapis.com;

        if ($request_uri ~ ^(.*/)/($|\?.*)) {
            return 200 '$1$2';
            return 301 $1$2;
        }

        if ($host != 'devstorye.us' ) {
            set $temp_cache 1$temp_cache;
        }

        if ($uri = '/') {
            set $temp_cache 1$temp_cache;
        }

        if ($temp_cache = 11) {

            proxy_pass $baseurl/cur-layout-dev-data/$cert_folder/$cert_folder;
            break;
        }
        if ($temp_cache = 1 ) {
            proxy_pass $baseurl/cur-layout-dev-data/$cert_folder$request_uri;
        }


    }

    ssl_certificate /etc/letsencrypt/live/app.nmedia2.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/app.nmedia2.com/privkey.pem;


}
