server {
    listen 80;
    listen [::]:80;
    server_name prompt-1.nmediax.com ;
    location ^~ /.well-known {
        root /app/ssl-folder/prompt-1.nmediax.com;
        break;
    }
    location / {
        return 301 https://$host$request_uri;
    }


}


server {
    server_name prompt-1.nmediax.com;
    rewrite ^/(.*)/$ /$1 permanent;
    listen 443 ssl;
    listen [::]:443 ssl;

    location / {
        proxy_pass http://aiwebadmin:6002;
    }
    location ~ .(static)/(js|css|media)/(.+)$ {
        proxy_pass http://aiwebadmin:6002;
    }

    ssl_certificate /etc/letsencrypt/live/prompt-1.nmediax.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/prompt-1.nmediax.com/privkey.pem;

}
