
server {
    listen 80;
    listen [::]:80;
    server_name api-prompt-1.nmediax.com ;
    location ^~ /.well-known {
        root /app/ssl-folder/api-prompt-1.nmediax.com;
        break;
    }
    location / {
        return 301 https://$host$request_uri;
    }

}


server {

    server_name api-prompt-1.nmediax.com;
    rewrite ^/(.*)/$ /$1 permanent;
    listen 443 ssl;
    listen [::]:443 ssl;

    location / {
        #include uwsgi_params;
        # uwsgi_pass unix:/home/curadmin/cr-api-server/curious-reads-server/app/crserver.sock;
       # proxy_read_timeout 600s;
       # uwsgi_read_timeout 600s;
       # include uwsgi_params;
       # uwsgi_pass aibridge:8086;
          proxy_pass http://aibridge:8086;
        #return 200 'hello';
        proxy_set_header Host "$http_host";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        add_header 'Access-Control-Allow-Origin' '*' always;
        client_max_body_size 200M;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
        add_header "Access-Control-Allow-Headers" "Authorization, Origin, X-Requested-With, Content-Type, Accept";
        if ($request_method = OPTIONS) {
            break;
        }
    }


    ssl_certificate /etc/letsencrypt/live/api-prompt-1.nmediax.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api-prompt-1.nmediax.com/privkey.pem;

}
