server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    # Allow Let's Encrypt challenge path
    location  /.well-known/acme-challenge/ {
        allow all;
#        root /var/www/certbot;
         root /app/ssl-folder/api.nmediax.com;
          break;
    }

    location ^~ /sslcreate {

        include uwsgi_params;
        uwsgi_pass sslserver:8085;

    }


 

}
